FROM node:16 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --ignore-scripts @nestjs/cli 

COPY prisma ./prisma/

RUN yarn install

COPY . .

EXPOSE 8080

CMD [ "yarn", "start:dev" ]