version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      PGDATA: /data/postgres
    expose:
      - "5432"
    volumes:
      - postgres:/data/postgres
    command: -p 5432
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres:
