version: "3.9"
networks:
  redis:
  redis-gui:
services:
  # ms-price-update:
  #   container_name: ms-price-update
  #   image: ms-price-update:latest
  #   ports:
  #     - 8080:8080
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: "curl -sS http://3xa:8080/health"
  #     interval: 1s
  #     timeout: 30s
  #     retries: 6
  redis:
    image: redis:6.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - redis:/data
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=host.docker.internal:redis:6379
    ports:
      - "8081:8081"
    networks:
      - redis
      - redis-gui
volumes:
  redis:
    driver: local
